sudo: required
services:
  - docker

before_install: 
  - sudo docker build -t meltwater/executive_alerts_intelligence .
  - sudo docker images
# - sudo docker run --rm --name executive_alerts_intelligence_container -p 5001:5001 \
# -   		          -e "AWS_ACCESS_KEY_ID=00000000000000000" \
# -   		          -e "AWS_SECRET_ACCESS_KEY=00000000000000000000" \
# -   		          -e "LUIGI_S3_BUCKET=encorealert-luigi-test" \
# -   		          -it meltwater/executive_alerts_intelligence

script: 
  - sudo docker run meltwater/executive_alerts_intelligence /bin/sh -c "cat /app/application.py"